# Generated by kaggle/bundle.py — edit the sources, not this file.
import sys as _sys
import types as _types

_m = _types.ModuleType('dreams_backbone')
_sys.modules['dreams_backbone'] = _m
exec(compile(r'''"""DreaMS backbone (Bushuiev et al., Nat. Biotechnol. 2025) as a plain torch module, for fine-tuning on our data.

The layer code below is adapted from the official release, github.com/pluskal-lab/DreaMS @ dbec3a0b
(dreams/models/dreams/{dreams,layers}.py, dreams/models/layers/{fourier_features,feed_forward}.py),
MIT License, Copyright (c) the DreaMS developers. Parameter names match the official modules, so the
self-supervised GeMS checkpoint (ssl_model.ckpt, Zenodo 10997887 / huggingface.co/roman-bushuiev/DreaMS) loads
with a strict key check. Only the forward pass of the encoder is kept (no Lightning, no SSL heads, no data code).

Input: (B, 1 + n, 2) float — token 0 is the precursor (m/z, 1.1), then up to n peaks (m/z in Da, intensity
relative to the base peak, ≤ 1); padding rows are all zero (m/z == 0 marks padding).
Output: (B, 1 + n, d_model); the precursor token [:, 0] is the spectrum embedding.
"""

import pickle
import types
from argparse import Namespace
from math import ceil

import numpy as np
import torch
import torch.nn.functional as F
from torch import nn
from torch.nn import Parameter

PREC_INTENS = 1.1  # official SpectrumPreprocessor precursor-token intensity


class FourierFeatures(nn.Module):
    def __init__(self, strategy, x_min, x_max, trainable=True, funcs="both", sigma=10, num_freqs=512):
        super().__init__()
        assert strategy in {"random", "voronov_et_al", "lin_float_int"} and x_min < 1
        self.funcs = funcs
        if strategy == "random":
            b = torch.randn(num_freqs) * sigma
        elif strategy == "voronov_et_al":
            b = torch.tensor([1 / (x_min * (x_max / x_min) ** (2 * i / (num_freqs - 2))) for i in range(1, num_freqs)])
        else:  # lin_float_int
            b = torch.tensor([1 / (x_min * i) for i in range(2, ceil(1 / x_min), 2)] +
                             [1 / (1 * i) for i in range(2, ceil(x_max), 1)])
        self.b = nn.Parameter(b.unsqueeze(0), requires_grad=trainable)
        self.register_parameter("Fourier frequencies", self.b)

    def forward(self, x):
        x = 2 * torch.pi * x @ self.b
        if self.funcs == "both":
            return torch.cat((torch.cos(x), torch.sin(x)), dim=-1)
        return torch.cos(x) if self.funcs == "cos" else torch.sin(x)

    def num_features(self):
        return self.b.shape[1] if self.funcs != "both" else 2 * self.b.shape[1]


def _interpolate(a, b, n):
    return [int(round(v)) for v in np.linspace(a, b, n + 2)[1:-1]]


class FeedForward(nn.Module):
    def __init__(self, in_dim, out_dim, hidden_dim, depth=None, act_last=True, act=nn.ReLU, bias=True, dropout=0):
        super().__init__()
        if isinstance(hidden_dim, int):
            hidden_dim = [hidden_dim] * depth
        elif hidden_dim == "interpolated":
            hidden_dim = _interpolate(in_dim, out_dim, depth - 1)
        else:
            depth = len(hidden_dim)
        layers = []
        for i in range(depth):
            d1 = hidden_dim[i - 1] if i != 0 else in_dim
            d2 = hidden_dim[i] if i != depth - 1 else out_dim
            layers.append(nn.Linear(d1, d2, bias=bias))
            if i != depth - 1:
                layers.append(nn.Dropout(p=dropout))
            if i != depth - 1 or act_last:
                layers.append(act())
        self.ff = nn.Sequential(*layers)

    def forward(self, x):
        return self.ff(x)


class MultiheadAttention(nn.Module):
    def __init__(self, a):
        super().__init__()
        self.d_model, self.n_heads, self.dropout = a.d_model, a.n_heads, a.att_dropout
        self.use_bias = not a.no_transformer_bias
        self.attn_mech = a.attn_mech
        self.d_graphormer_params = a.d_graphormer_params
        self.head_dim = self.d_model // self.n_heads
        self.scale = self.head_dim ** -0.5
        self.weights = Parameter(torch.empty(4 * self.d_model, self.d_model))
        nn.init.normal_(self.weights, 0, (2 / (5 * self.d_model)) ** 0.5)
        if self.use_bias:
            self.biases = Parameter(torch.zeros(4 * self.d_model))
        if self.d_graphormer_params:
            self.lin_graphormer = nn.Linear(self.d_graphormer_params, self.n_heads, bias=False)
        if self.attn_mech == "additive_v":
            self.additive_v = Parameter(torch.empty(self.n_heads, self.head_dim))
            nn.init.normal_(self.additive_v, 0, (2 / (5 * self.d_model)) ** 0.5)

    def _proj(self, x, start=0, end=None):
        return F.linear(x, self.weights[start:end], None if not self.use_bias else self.biases[start:end])

    def forward(self, x, mask, four=None):
        """`four`: (bs, n, d_fourier) Fourier token features. The official bias lin(f_i - f_j) over the
        (bs, n, n, d_fourier) difference tensor equals p_i - p_j with p = lin(f) (linear, no bias): computed
        per token, without the pairwise tensor."""
        bs, n, _ = x.size()
        q, k, v = self._proj(x, end=3 * self.d_model).chunk(3, dim=-1)
        sp = lambda t: t.reshape(bs, n, self.n_heads, self.head_dim).transpose(1, 2)  # noqa: E731
        q, k, v = sp(q), sp(k), sp(v)
        if self.attn_mech == "dot-product":
            att = torch.einsum("bhnd,bhdm->bhnm", q, k.transpose(-2, -1))
        else:
            att = q.unsqueeze(-2) - k.unsqueeze(-3)
            if self.attn_mech == "additive_v":
                att = att * self.additive_v.unsqueeze(0).unsqueeze(2).unsqueeze(3)
            att = att.sum(dim=-1)
        att = att * self.scale
        if four is not None:
            if self.d_graphormer_params:
                p = self.lin_graphormer(four)  # (bs, n, heads)
                att = att + (p.unsqueeze(2) - p.unsqueeze(1)).permute(0, 3, 1, 2)
            else:
                p = four.sum(dim=-1)  # (bs, n)
                att = att + (p.unsqueeze(2) - p.unsqueeze(1)).unsqueeze(1)
        if mask is not None:  # official code masks query rows of padding tokens (keys stay visible)
            att = att.masked_fill(mask.unsqueeze(1).unsqueeze(-1), -1e9)
        att = F.dropout(F.softmax(att.float(), dim=-1).to(v.dtype), p=self.dropout, training=self.training)
        out = (att @ v).transpose(1, 2).reshape(bs, n, -1)
        return self._proj(out, start=3 * self.d_model)


class TFeedForward(nn.Module):
    def __init__(self, a):
        super().__init__()
        self.dropout = a.ff_dropout
        bias = not a.no_transformer_bias
        self.in_proj = nn.Linear(a.d_model, 4 * a.d_model, bias=bias)
        self.out_proj = nn.Linear(4 * a.d_model, a.d_model, bias=bias)

    def forward(self, x):
        return self.out_proj(F.dropout(F.relu(self.in_proj(x)), p=self.dropout, training=self.training))


class ScaleNorm(nn.Module):
    def __init__(self, scale, eps=1e-5):
        super().__init__()
        self.scale = Parameter(torch.tensor(scale))
        self.eps = eps

    def forward(self, x):
        return x * (self.scale / torch.norm(x, dim=-1, keepdim=True).clamp(min=self.eps))


class TransformerEncoder(nn.Module):
    def __init__(self, a):
        super().__init__()
        self.residual_dropout, self.n_layers, self.pre_norm = a.residual_dropout, a.n_layers, a.pre_norm
        self.atts = nn.ModuleList([MultiheadAttention(a) for _ in range(a.n_layers)])
        self.ffs = nn.ModuleList([TFeedForward(a) for _ in range(a.n_layers)])
        n_sc = a.n_layers * 2 + 1 if a.pre_norm else a.n_layers * 2
        self.scales = nn.ModuleList([ScaleNorm(a.d_model ** 0.5) if a.scnorm else nn.LayerNorm(a.d_model)
                                     for _ in range(n_sc)])
        self.checkpointing = False

    def _layer(self, i, x, mask, gd):
        att_scale, ff_scale = self.scales[2 * i], self.scales[2 * i + 1]
        r = x
        x = att_scale(x) if self.pre_norm else x
        x = r + F.dropout(self.atts[i](x, mask, gd), p=self.residual_dropout, training=self.training)
        x = x if self.pre_norm else att_scale(x)
        r = x
        x = ff_scale(x) if self.pre_norm else x
        x = r + F.dropout(self.ffs[i](x), p=self.residual_dropout, training=self.training)
        return x if self.pre_norm else ff_scale(x)

    def forward(self, x, mask, gd=None):
        x = F.dropout(x, p=self.residual_dropout, training=self.training)
        for i in range(self.n_layers):
            if self.checkpointing and self.training:
                x = torch.utils.checkpoint.checkpoint(self._layer, i, x, mask, gd, use_reentrant=False)
            else:
                x = self._layer(i, x, mask, gd)
        return self.scales[-1](x) if self.pre_norm else x


class DreaMSBackbone(nn.Module):
    """Encoder part of the official `DreaMS` LightningModule (same parameter names)."""

    def __init__(self, args: Namespace, max_mz: float, max_tbxic_stdev: float):
        super().__init__()
        a = Namespace(**vars(args))
        a.d_model = sum(d for d in [a.d_fourier, a.d_peak, getattr(a, "d_mz_token", 0)] if d)
        a.d_graphormer_params = (a.d_fourier if a.d_fourier else 1) \
            if (a.graphormer_mz_diffs and a.graphormer_parametrized) else 0
        assert a.d_fourier and not a.vanilla_transformer, "only the published configuration is supported"
        self.a, self.max_mz, self.d_model = a, float(max_mz), a.d_model
        self.max_tbxic_stdev = float(max_tbxic_stdev)
        self.charge_feature = bool(a.charge_feature)
        self.fourier_enc = FourierFeatures(a.fourier_strategy, num_freqs=a.fourier_num_freqs,
                                           x_min=a.fourier_min_freq or max_tbxic_stdev, x_max=max_mz,
                                           trainable=a.fourier_trainable)
        self.ff_fourier = FeedForward(self.fourier_enc.num_features(), a.d_fourier, a.ff_fourier_d,
                                      depth=a.ff_fourier_depth, dropout=a.dropout, bias=not a.no_ffs_bias)
        self.ff_peak = FeedForward(3 if a.charge_feature else 2, a.d_peak, a.d_peak, depth=a.ff_peak_depth,
                                   dropout=a.dropout, bias=not a.no_ffs_bias)
        self.transformer_encoder = TransformerEncoder(a)

    def forward(self, spec, charge=None):
        pad = spec[:, :, 0] == 0
        if self.charge_feature:
            c = torch.ones(spec.shape[0], device=spec.device, dtype=spec.dtype) if charge is None else charge
            spec = torch.cat([spec, (~pad * c.unsqueeze(-1)).unsqueeze(-1).to(spec.dtype)], dim=-1)
        norm = torch.ones(spec.shape[-1], device=spec.device, dtype=spec.dtype)
        norm[0] = self.max_mz
        peak = self.ff_peak(spec / norm)
        # Fourier features of m/z up to 5,000 cycles/Da: phases must be computed in float32 (never fp16)
        with torch.autocast(device_type=spec.device.type, enabled=False):
            ff = self.fourier_enc(spec[..., [0]].float())
        four = self.ff_fourier(ff)
        x = torch.cat([peak.to(four.dtype), four], dim=-1)
        return self.transformer_encoder(x, pad, four if self.a.graphormer_mz_diffs else None)


# --- checkpoint loading without the dreams / msml packages ----------------------------------------------------

class _Stub:
    def __init__(self, *a, **k):
        pass

    def __setstate__(self, state):
        self.__dict__.update(state if isinstance(state, dict) else {"_state": state})


class _Unpickler(pickle.Unpickler):
    def find_class(self, module, name):
        try:
            return super().find_class(module, name)
        except Exception:  # noqa: BLE001 — classes of packages we do not install (dreams, msml)
            return type(name, (_Stub,), {"__module__": module})


_PICKLE = types.SimpleNamespace(Unpickler=_Unpickler, load=pickle.load, __name__="pickle")


def read_checkpoint(path):
    """(hparams args Namespace, dformat attrs dict, state_dict) of an official Lightning checkpoint."""
    ck = torch.load(path, map_location="cpu", weights_only=False, pickle_module=_PICKLE)
    hp = ck["hyper_parameters"]
    args = hp["args"]
    df = getattr(args, "dformat", None)
    # data-format settings are class attributes of dreams.utils.dformats (not pickled): by class name
    known = {"DataFormatA": dict(max_mz=1000.0, max_tbxic_stdev=1e-4, max_prec_mz=1000.0, max_peaks_n=128),
             "DataFormatB": dict(max_mz=1500.0, max_tbxic_stdev=1e-3, max_prec_mz=1500.0, max_peaks_n=128),
             "DataFormatC": dict(max_mz=1500.0, max_tbxic_stdev=1e-3, max_prec_mz=1500.0, max_peaks_n=128)}
    name = type(df).__name__ if df is not None else "DataFormatA"
    if name not in known:
        raise RuntimeError(f"unknown DreaMS data format {name}")
    dformat = dict(known[name], name=name)
    return args, dformat, ck["state_dict"], hp


def load_backbone(path, prefix=None):
    """DreaMSBackbone with the checkpoint's weights (strict on every backbone parameter)."""
    args, dformat, sd, _ = read_checkpoint(path)
    max_mz = dformat.get("max_mz", 1000.0)
    tb = dformat.get("max_tbxic_stdev", 1e-4)
    net = DreaMSBackbone(args, max_mz, tb)
    if prefix is None:  # ssl_model: no prefix; fine-tuning heads: "backbone."
        prefix = "backbone." if any(k.startswith("backbone.") for k in sd) else ""
    own = {k[len(prefix):]: v for k, v in sd.items() if k.startswith(prefix)}
    want = net.state_dict()
    missing = [k for k in want if k not in own]
    shape = [k for k in want if k in own and tuple(own[k].shape) != tuple(want[k].shape)]
    if missing or shape:
        raise RuntimeError(f"DreaMS checkpoint mismatch: missing {missing[:8]}, shape {shape[:8]}")
    net.load_state_dict({k: own[k].float() for k in want})
    return net, args, dformat


def prep_spectrum(mz, it, prec_mz, n_peaks=100):
    """Official preprocessing: n highest peaks, intensities relative to the base peak, precursor token first,
    zero-padded to 1 + n_peaks rows. Returns float32 (1 + n_peaks, 2)."""
    mz = np.asarray(mz, np.float64)
    it = np.asarray(it, np.float64)
    ok = (it > 0) & (mz > 0)
    mz, it = mz[ok], it[ok]
    out = np.zeros((1 + n_peaks, 2), np.float32)
    out[0] = (prec_mz, PREC_INTENS)
    if len(mz):
        sel = np.argsort(it)[-n_peaks:]
        sel = sel[np.argsort(mz[sel])]
        out[1:1 + len(sel), 0] = mz[sel]
        out[1:1 + len(sel), 1] = it[sel] / it.max()
    return out


# --- our fingerprint model on top of the backbone -------------------------------------------------------------

class DreamsFP(nn.Module):
    """Spectrum -> fingerprint-bit logits: DreaMS backbone, then [precursor token, mean of peak tokens, condition
    embedding (adduct, instrument family, collision energy, polarity, precursor m/z)] -> MLP -> nbits.
    Vocabulary sizes are passed in (casmi.fpmodel.ADDUCT_LIST / INSTR_LIST) to keep this module dependency-free."""

    def __init__(self, backbone: DreaMSBackbone, nbits: int, n_adducts: int, n_instr: int, d_cond=64, hidden=2048,
                 drop=0.1):
        super().__init__()
        self.backbone = backbone
        d = backbone.d_model
        self.ad = nn.Embedding(n_adducts, d_cond)
        self.ins = nn.Embedding(n_instr, d_cond)
        self.cond = nn.Linear(3, d_cond)
        self.head = nn.Sequential(nn.LayerNorm(2 * d + d_cond), nn.Linear(2 * d + d_cond, hidden), nn.GELU(),
                                  nn.Dropout(drop), nn.Linear(hidden, nbits))
        self.nbits, self.d_cond, self.hidden = nbits, d_cond, hidden

    def forward(self, spec, ad, ins, ce, mode):
        h = self.backbone(spec)
        real = (spec[:, 1:, 0] != 0).to(h.dtype)
        mean = (h[:, 1:] * real.unsqueeze(-1)).sum(1) / real.sum(1, keepdim=True).clamp(min=1)
        c = self.ad(ad) + self.ins(ins) + self.cond(torch.stack([ce / 100.0, mode, spec[:, 0, 0] / 1000.0], -1)
                                                    .to(h.dtype))
        return self.head(torch.cat([h[:, 0], mean, c.to(h.dtype)], -1))


_PRIMS = (int, float, str, bool, type(None))


def save_fp(net: DreamsFP, path, n_peaks: int, extra=None):
    """Tensors + primitives only (loads with weights_only=True). fp16 weights except the Fourier frequencies,
    which must stay float32 (up to 5,000 cycles/Da)."""
    sd = {k: (v.detach().float().cpu() if k.startswith("backbone.fourier_enc.") else v.detach().half().cpu())
          for k, v in net.state_dict().items()}
    bb = net.backbone
    meta = {"kind": "dreams_fp", "nbits": net.nbits, "n_adducts": net.ad.num_embeddings,
            "n_instr": net.ins.num_embeddings, "d_cond": net.d_cond, "hidden": net.hidden, "n_peaks": int(n_peaks),
            "max_mz": bb.max_mz, "max_tbxic_stdev": bb.max_tbxic_stdev,
            "args": {k: v for k, v in vars(bb.a).items() if isinstance(v, _PRIMS)}}
    meta.update(extra or {})
    torch.save({"model": sd, **meta}, path)


def load_fp(path, device="cpu"):
    ck = torch.load(path, map_location="cpu", weights_only=True)
    args = Namespace(**ck["args"])
    bb = DreaMSBackbone(args, ck["max_mz"], ck["max_tbxic_stdev"])
    net = DreamsFP(bb, int(ck["nbits"]), int(ck["n_adducts"]), int(ck["n_instr"]), int(ck["d_cond"]),
                   int(ck["hidden"]))
    net.load_state_dict({k: v.float() for k, v in ck["model"].items()})  # strict
    net.n_peaks = int(ck["n_peaks"])
    net.kind = "dreams_fp"
    return net.to(device).eval()


@torch.no_grad()
def fp_logits(net: DreamsFP, raw, precs, ad_idx, ins_idx, ces, modes, batch=256):
    """(n_spectra, nbits) logits. raw: list of (mz, intensity) arrays (as measured), the rest per spectrum."""
    dev = next(net.parameters()).device
    X = np.stack([prep_spectrum(mz, it, pm, net.n_peaks) for (mz, it), pm in zip(raw, precs)])
    out = []
    for a in range(0, len(X), batch):
        sl = slice(a, a + batch)
        T = lambda v, dt=torch.float32: torch.as_tensor(np.asarray(v[sl]), dtype=dt, device=dev)  # noqa: E731
        out.append(net(T(X), T(ad_idx, torch.long), T(ins_idx, torch.long), T(ces), T(modes)).float().cpu().numpy())
    return np.concatenate(out) if out else np.zeros((0, net.nbits), np.float32)
''', 'dreams_backbone.py', 'exec'), _m.__dict__)

"""Fine-tune the DreaMS backbone (self-supervised on GeMS, the public MassIVE/GNPS spectra; ssl_model.ckpt) to predict
our fingerprint bits from the competition train file — our own model on a pretrained encoder.

Same targets / exclusions / loss as FP run 3 (pure BCE over the informative bits; the held-out validation
structures are excluded by row_struct == -2), DreaMS preprocessing (n highest peaks, intensities relative to the base
peak, precursor token first). The model is casmi.dreams_backbone.DreamsFP (bundled into this script by
kaggle/bundle.py); the weights come from the output of our casmi26-dreams-probe kernel (official release).

Kaggle GPU script. Inputs: competition data; vigneshnehru/casmi26-fp-train (row_struct.npy, fp_targets.npy,
decoys.npy, nbits.txt); vigneshnehru/casmi26-artifacts (code__fpmodel.py: adduct / instrument vocabularies);
vigneshnehru/casmi26-dreams-probe (dreams_weights/ssl_model.ckpt).
Output (/kaggle/working): dreams_fp.pt (casmi.dreams_backbone.load_fp), train_log.csv
"""

import glob
import math
import os
import shutil
import sys
import time
from multiprocessing import Pool

import numpy as np
import pyarrow.compute as pc
import pyarrow.parquet as pq
import torch
import torch.nn as nn
import torch.nn.functional as F

import dreams_backbone as DB

T_START = time.time()
BUDGET_S = float(os.environ.get("FP_BUDGET_S", 10.6 * 3600))  # Kaggle GPU sessions stop at 12 h
SMOKE = os.environ.get("FP_SMOKE") == "1"  # local CPU check: random tiny backbone, one row group, few steps
DS = os.environ.get("FP_DS") or os.path.dirname(glob.glob("/kaggle/input/**/fp_targets.npy", recursive=True)[0])
TRAIN = os.environ.get("FP_TRAIN") or glob.glob("/kaggle/input/**/train.parquet", recursive=True)[0]
_CODE = glob.glob("/kaggle/input/**/code__fpmodel.py", recursive=True)
if _CODE:
    os.makedirs("/kaggle/working/fpcode", exist_ok=True)
    shutil.copy(_CODE[0], "/kaggle/working/fpcode/fpmodel.py")
    sys.path.insert(0, "/kaggle/working/fpcode")
else:
    sys.path.insert(0, os.environ.get("FP_CODE", DS))
import fpmodel as M  # noqa: E402

N_PEAKS = int(os.environ.get("FP_NPEAKS", 60))
BS = 16 if SMOKE else int(os.environ.get("FP_BS", 128))
LR_BB, LR_HEAD, WD, WARM = 5e-5, 5e-4, 0.01, (5 if SMOKE else 1500)
ENVEDA_POS_SHIFT = -0.0004
OUT = os.environ.get("FP_OUT", "/kaggle/working")
print("dataset", DS, "train", TRAIN, "gpus", torch.cuda.device_count(), "peaks", N_PEAKS, "batch", BS, flush=True)


def _rg(rg):
    f = pq.ParquetFile(TRAIN)
    rs = np.load(os.path.join(DS, "row_struct.npy"), mmap_mode="r")
    start = sum(f.metadata.row_group(i).num_rows for i in range(rg))
    n = f.metadata.row_group(rg).num_rows
    lab = np.asarray(rs[start:start + n])
    sel = np.flatnonzero(lab != -1)
    tbl = f.read_row_group(rg, columns=["ms2_mzs", "ms2_normalized_intensities", "precursor_mz", "adduct",
                                        "instrument_type", "ionization_mode", "collision_energy_ev",
                                        "ingest_lib"]).take(sel)
    mzs, its = tbl["ms2_mzs"].combine_chunks(), tbl["ms2_normalized_intensities"].combine_chunks()
    off = mzs.offsets.to_numpy()
    fm = pc.list_flatten(mzs).to_numpy(zero_copy_only=False)
    fi = pc.list_flatten(its).to_numpy(zero_copy_only=False)
    prec = tbl["precursor_mz"].to_numpy(zero_copy_only=False).astype(np.float64)
    pos = np.asarray(tbl["ionization_mode"].to_pylist()) == "positive"
    lib = np.asarray(tbl["ingest_lib"].to_pylist())
    shift = np.where(pos & np.isin(lib, ["enveda-180", "enveda-np-examples"]), ENVEDA_POS_SHIFT, 0.0)
    prec = prec + shift
    ce = np.array([np.mean(c) if c else 0.0 for c in tbl["collision_energy_ev"].to_pylist()], np.float32)
    k = len(sel)
    MZ = np.zeros((k, 1 + N_PEAKS), np.float32)
    IT = np.zeros((k, 1 + N_PEAKS), np.float16)
    for j in range(k):
        a, b = off[j], off[j + 1]
        x = DB.prep_spectrum(fm[a:b] + shift[j], fi[a:b], prec[j], N_PEAKS)
        MZ[j], IT[j] = x[:, 0], x[:, 1]
    ad = np.array([M.ADDUCT_IX.get(a, M.ADDUCT_IX["<unk>"]) for a in tbl["adduct"].to_pylist()], np.int16)
    ins = np.array([M.instr_family(s) for s in tbl["instrument_type"].to_pylist()], np.int8)
    return MZ, IT, ad, ins, ce, pos.astype(np.float32), lab[sel]


def load_data():
    nrg = 1 if SMOKE else pq.ParquetFile(TRAIN).num_row_groups
    with Pool(4) as p:
        parts = p.map(_rg, range(nrg), chunksize=1)
    cat = [np.concatenate([q[i] for q in parts]) for i in range(7)]
    keep = (cat[0][:, 1] > 0)  # at least one peak
    print(f"prepared {keep.sum():,} spectra in {time.time() - T_START:.0f}s", flush=True)
    return [c[keep] for c in cat]


def backbone():
    if SMOKE:
        from argparse import Namespace
        a = Namespace(d_fourier=40, d_peak=24, d_mz_token=None, n_layers=2, n_heads=4, att_dropout=0.1, ff_dropout=0.1,
                      residual_dropout=0.1, dropout=0.1, no_transformer_bias=False, attn_mech="dot-product",
                      pre_norm=False, scnorm=False, graphormer_mz_diffs=True, graphormer_parametrized=True,
                      fourier_strategy="lin_float_int", fourier_num_freqs=None, fourier_min_freq=None,
                      fourier_trainable=False, ff_fourier_d=32, ff_fourier_depth=2, ff_peak_depth=2, no_ffs_bias=False,
                      charge_feature=False, vanilla_transformer=False)
        return DB.DreaMSBackbone(a, 1000.0, 1e-2)
    ck = glob.glob("/kaggle/input/**/ssl_model.ckpt", recursive=True)[0]
    net, args, dformat = DB.load_backbone(ck)
    print("DreaMS backbone", ck, "params", sum(p.numel() for p in net.parameters()), "d_model", net.d_model,
          "dformat", dformat, flush=True)
    return net


def main():
    MZ, IT, AD, INS, CE, MODE, LAB = load_data()
    fps = np.load(os.path.join(DS, "fp_targets.npy"))
    nbits = int(open(os.path.join(DS, "nbits.txt")).read())
    dev = torch.device("cpu" if SMOKE else "cuda")
    tr = np.flatnonzero(LAB >= 0)
    rng = np.random.default_rng(0)
    mon = rng.choice(tr, min(20000, len(tr) // 10), replace=False)
    tr = np.setdiff1d(tr, mon)
    print(f"train {len(tr):,}  monitor {len(mon):,}  nbits {nbits}", flush=True)

    g = lambda a, dt=None: torch.as_tensor(a if dt is None else a.astype(dt)).to(dev)  # noqa: E731
    gMZ, gIT = g(MZ), g(IT)
    gAD, gINS, gCE, gMODE = g(AD, np.int64), g(INS, np.int64), g(CE), g(MODE)
    gLAB, gFP = g(np.maximum(LAB, 0), np.int64), g(fps)
    gDEC = g(np.load(os.path.join(DS, "decoys.npy")), np.int64)
    del MZ, IT
    shifts = torch.arange(7, -1, -1, device=dev, dtype=torch.uint8)

    def batch(idx, aug):
        idx = torch.as_tensor(idx, device=dev)
        mz, it = gMZ[idx], gIT[idx].float()
        if aug:  # drop 10 % of the peaks (never the precursor token nor all peaks), jitter intensities
            real = mz[:, 1:] > 0
            drop = (torch.rand(real.shape, device=dev) < 0.1) & real
            drop &= drop.sum(1, keepdim=True) < real.sum(1, keepdim=True)
            mz = mz.clone()
            mz[:, 1:] = mz[:, 1:].masked_fill(drop, 0.0)
            it = it.clone()
            it[:, 1:] = (it[:, 1:] * torch.exp(0.1 * torch.randn_like(it[:, 1:]))).clamp(0, 1).masked_fill(
                mz[:, 1:] == 0, 0.0)
        spec = torch.stack([mz, it], -1)
        lab = gLAB[idx]
        cand = torch.cat([lab[:, None], gDEC[lab]], 1)
        yc = ((gFP[cand.clamp(min=0)][..., None] >> shifts) & 1).reshape(len(idx), cand.shape[1], -1)[..., :nbits]
        return (spec, gAD[idx], gINS[idx], gCE[idx], gMODE[idx]), yc[:, 0].float(), (yc, cand >= 0)

    def contrastive(z, yc, valid):
        s = torch.einsum("bkn,bn->bk", yc.float(), z.float()).masked_fill(~valid, float("-inf"))
        return (s.argmax(1) == 0).float().mean(), valid.sum(1).float().mean()

    net = DB.DreamsFP(backbone(), nbits, len(M.ADDUCT_LIST), len(M.INSTR_LIST)).to(dev)
    model = nn.DataParallel(net) if torch.cuda.device_count() > 1 else net
    bb_params = list(net.backbone.parameters())
    bb_ids = {id(p) for p in bb_params}
    head_params = [p for p in net.parameters() if id(p) not in bb_ids]
    opt = torch.optim.AdamW([{"params": [p for p in bb_params if p.requires_grad], "lr": LR_BB, "base": LR_BB},
                             {"params": head_params, "lr": LR_HEAD, "base": LR_HEAD}],
                            weight_decay=WD, betas=(0.9, 0.98))
    scaler = torch.amp.GradScaler(enabled=not SMOKE)
    steps_per_epoch = 20 if SMOKE else len(tr) // BS
    total, step, ep = None, 0, 0
    t_train = time.time()
    last_save = time.time()
    log = open(os.path.join(OUT, "train_log.csv"), "w")
    log.write("epoch,step,train_bce,mon_bce,mon_top1_in_window,mon_cands,lr_bb,elapsed_s\n")

    def factor(s):
        if s < WARM:
            return (s + 1) / WARM
        if total is None:
            return 1.0
        return 0.5 * (1 + math.cos(math.pi * min(1.0, (s - WARM) / max(1, total - WARM))))

    def save():
        DB.save_fp(net, os.path.join(OUT, "dreams_fp.pt"), N_PEAKS, extra={"steps": step, "epochs": ep})

    def evaluate():
        model.eval()
        ml = acc = ncand = 0.0
        with torch.no_grad(), torch.autocast("cuda", dtype=torch.float16, enabled=not SMOKE):
            for b in range(0, len(mon), 512):
                x, y, (yc, valid) = batch(mon[b:b + 512], False)
                z = model(*x).float()
                ml += F.binary_cross_entropy_with_logits(z, y, reduction="sum").item()
                a, nc = contrastive(z, yc, valid)
                acc += a.item() * len(y)
                ncand += nc.item() * len(y)
        model.train()
        return ml / (len(mon) * nbits), acc / len(mon), ncand / len(mon)

    done = False
    while not done:
        perm = rng.permutation(tr)
        run, nrun = 0.0, 0
        model.train()
        for b in range(steps_per_epoch):
            x, y, _ = batch(perm[b * BS:(b + 1) * BS], True)
            f = factor(step)
            for gp in opt.param_groups:
                gp["lr"] = gp["base"] * f
            with torch.autocast("cuda", dtype=torch.float16, enabled=not SMOKE):
                z = model(*x)
            loss = F.binary_cross_entropy_with_logits(z.float(), y)
            opt.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.unscale_(opt)
            nn.utils.clip_grad_norm_(net.parameters(), 1.0)
            scaler.step(opt)
            scaler.update()
            if b % 50 == 0:
                run += loss.item()
                nrun += 1
            step += 1
            if total is None and step == (10 if SMOKE else 300):
                rate = step / (time.time() - t_train)
                remain = BUDGET_S - (time.time() - T_START) - 900
                total = int(min((2 if SMOKE else 30) * steps_per_epoch, step + remain * rate))
                print(f"{rate:.2f} steps/s ({rate * BS:.0f} spectra/s); total steps {total:,} "
                      f"(~{total / steps_per_epoch:.2f} epochs)", flush=True)
            if step % (5 if SMOKE else 2000) == 0:
                print(f"  step {step:,} loss {loss.item():.5f} lr_bb {opt.param_groups[0]['lr']:.2e} "
                      f"{time.time() - T_START:.0f}s", flush=True)
            if time.time() - last_save > 2700:  # checkpoint every 45 min: a timeout must not lose the run
                save()
                last_save = time.time()
            if total is not None and step >= total:
                done = True
                break
        ep += 1
        ml, acc, nc = evaluate()
        msg = (f"{ep},{step},{run / max(nrun, 1):.5f},{ml:.5f},{acc:.4f},{nc:.1f},{opt.param_groups[0]['lr']:.2e},"
               f"{time.time() - T_START:.0f}")
        print(msg, flush=True)
        log.write(msg + "\n")
        log.flush()
        save()
        last_save = time.time()
    print("done", time.time() - T_START, flush=True)


if __name__ == "__main__":
    main()
