"""Bundle a Kaggle script with modules from src/casmi into one file (script kernels are single files).

    python kaggle/bundle.py <script.py> <out.py> <module> [<module> ...]
Each module's source is embedded verbatim and registered in sys.modules under its own name before the script runs.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    src, out, *mods = sys.argv[1:]
    parts = ["# Generated by kaggle/bundle.py — edit the sources, not this file.\nimport sys as _sys\nimport types as _types\n"]
    for m in mods:
        code = (ROOT / "src" / "casmi" / f"{m}.py").read_text()
        assert "'''" not in code, f"{m}: triple single quotes cannot be embedded"
        parts.append(f"_m = _types.ModuleType({m!r})\n_sys.modules[{m!r}] = _m\n"
                     f"exec(compile(r'''{code}''', {m + '.py'!r}, 'exec'), _m.__dict__)\n")
    parts.append(Path(src).read_text())
    Path(out).write_text("\n".join(parts))
    print("bundled", out, [m for m in mods])


if __name__ == "__main__":
    main()
