"""Generate an evaluation kernel that fits and ships one chosen ranker variant (CASMI_FORCE) of
kaggle/moe_fp_pc/moe_fp_pc.py with a given set of kernel sources (FP models, GLACIER shards).

    python kaggle/make_forced.py <dir> <slug> "<variant name>" <kernel_source> [<kernel_source> ...]
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    d, slug, force, *sources = sys.argv[1:]
    out = ROOT / d
    out.mkdir(parents=True, exist_ok=True)
    src = (ROOT / "kaggle" / "moe_fp_pc" / "moe_fp_pc.py").read_text()
    pre = (f"# Generated by kaggle/make_forced.py from kaggle/moe_fp_pc/moe_fp_pc.py (edit that file).\n"
           f"import os\nos.environ[\"CASMI_FORCE\"] = {force!r}\n")
    code = f"{slug.replace('-', '_')}.py"
    (out / code).write_text(pre + src)
    meta = json.loads((ROOT / "kaggle" / "moe_fp_pc_lowpop" / "kernel-metadata.json").read_text())
    meta.update(id=f"vigneshnehru/{slug}", title=slug, code_file=code, kernel_sources=list(sources))
    (out / "kernel-metadata.json").write_text(json.dumps(meta, indent=2))
    print(out, code, force, sources)


if __name__ == "__main__":
    main()
